version: "3.9"
services:
  app:
    environment: 
      TZ: "${TZ:-Australia/Sydney}"
      NODE_ENV: production
    build:
      context: .
      dockerfile: "ruby-3.0.3-slim-bullseye.Dockerfile"

# add nginx postgres through alpine I think