version: "3"
services:
  app:
    build:
      context: .
      dockerfile: "ruby-3.0.3-slim-bullseye.Dockerfile"
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/usr/apps/openfoodnetwork/
      - bundles:/bundle
    environment:
      - BUNDLE_PATH=vendor/cache
volumes:
  bundles: